# Generated by Django 2.2.4 on 2019-08-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('tag', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Début de la saison')),
                ('end', models.DateTimeField(verbose_name='Fin de la saison')),
                ('title', models.CharField(max_length=255)),
                ('competitor', models.ManyToManyField(through='ranking.Elo', to='ranking.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('event_slug', models.CharField(max_length=255, null=True)),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Saison')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament_state')),
            ],
        ),
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullRoundText', models.CharField(max_length=255)),
                ('roundText', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('looser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser', to='ranking.Competitor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ranking.Competitor')),
            ],
        ),
        migrations.AddField(
            model_name='elo',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Saison'),
        ),
    ]
