# Generated by Django 2.2.4 on 2019-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20190819_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
