# Generated by Django 2.2.4 on 2019-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saison',
            name='prefix',
            field=models.CharField(default='Dijon', max_length=255),
        ),
        migrations.AlterField(
            model_name='saison',
            name='title',
            field=models.CharField(default='Saison', max_length=255),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='saison',
        ),
        migrations.AddField(
            model_name='tournament',
            name='saison',
            field=models.ManyToManyField(related_name='Saison', to='ranking.Saison'),
        ),
    ]
