# Generated by Django 2.2.4 on 2019-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20190822_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='nb_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elo',
            name='nb_tournament',
            field=models.IntegerField(default=0),
        ),
    ]
