# Generated by Django 2.2.4 on 2019-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0006_auto_20190823_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elo',
            name='nb_match',
        ),
        migrations.AddField(
            model_name='elo',
            name='nb_match_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elo',
            name='nb_match_win',
            field=models.IntegerField(default=0),
        ),
    ]
