# Generated by Django 2.2.4 on 2019-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='logo_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='association',
            name='site_url',
            field=models.URLField(default=''),
        ),
    ]
