# Generated by Django 2.2.4 on 2019-09-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0009_auto_20190904_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='logo_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='site_url',
            field=models.URLField(default='', null=True),
        ),
    ]
