# Generated by Django 2.2.4 on 2019-09-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0010_auto_20190909_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('icon_static', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='elo',
            name='main_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_char', to='ranking.Character'),
        ),
        migrations.AddField(
            model_name='elo',
            name='second_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_char', to='ranking.Character'),
        ),
        migrations.AddField(
            model_name='elo',
            name='third_char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_char', to='ranking.Character'),
        ),
    ]
