# Generated by Django 2.2.4 on 2019-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0011_auto_20190915_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='splash_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name_fr',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
