# Generated by Django 2.2.4 on 2019-09-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0012_auto_20190915_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='', null=True)),
                ('title', models.CharField(max_length=255)),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one', to='ranking.Elo')),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two', to='ranking.Elo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament')),
            ],
        ),
    ]
