# Generated by Django 2.2.4 on 2019-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0013_vod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='id_watch_video',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
