# Generated by Django 2.2.4 on 2019-10-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0014_vod_id_watch_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vod',
            name='player_one',
        ),
        migrations.RemoveField(
            model_name='vod',
            name='player_two',
        ),
    ]
