# Generated by Django 2.2.4 on 2019-10-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0015_auto_20191008_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vodplaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vod',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.Vodplaylist'),
        ),
    ]
