# Generated by Django 2.2.4 on 2019-10-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0016_auto_20191010_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='vodplaylist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
