# Generated by Django 2.2.4 on 2019-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0017_vodplaylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
