# Generated by Django 2.2.4 on 2019-10-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0020_auto_20191030_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament_place'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament_serie'),
        ),
        migrations.AlterField(
            model_name='tournament_place',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tournament_serie',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
