# Generated by Django 2.2.4 on 2019-11-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0022_tournament_serie_is_on_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchs',
            name='elo_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchs',
            name='elo_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='splash_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='fullRoundText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='looser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser', to='ranking.Elo'),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='roundText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='ranking.Elo'),
        ),
        migrations.AlterField(
            model_name='tournament_serie',
            name='is_on_pr',
            field=models.BooleanField(default=True, verbose_name='Possède des tournois du Power Ranking'),
        ),
    ]
