# Generated by Django 2.2.4 on 2019-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0023_auto_20191120_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchs',
            name='looser_elo_value_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchs',
            name='winner_elo_value_before',
            field=models.IntegerField(default=0),
        ),
    ]
