# Generated by Django 2.2.4 on 2019-11-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0024_auto_20191120_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
