# Generated by Django 2.2.4 on 2019-11-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0024_auto_20191120_1348'),
        ('ranking', '0023_auto_20191030_1638'),
    ]

    operations = [
    ]
