# Generated by Django 2.2.4 on 2020-03-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0026_auto_20200104_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nb_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament_serie',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.Tournament_place'),
        ),
    ]
