# Generated by Django 2.2.4 on 2020-03-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0027_auto_20200304_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament_serie',
            name='place',
        ),
        migrations.AddField(
            model_name='tournament_serie',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ranking.City'),
        ),
    ]
