# Generated by Django 2.2.4 on 2020-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0029_elo_is_away'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='is_main_saison',
            field=models.BooleanField(default=False, verbose_name='Saison Principale'),
        ),
    ]
