# Generated by Django 2.2.4 on 2020-03-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0030_saison_is_main_saison'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='annee_de_jeu',
            field=models.IntegerField(default=2),
        ),
    ]
