# Generated by Django 2.2.4 on 2020-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0031_saison_annee_de_jeu'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='eligibilty_percent',
            field=models.IntegerField(default=33),
        ),
    ]
