# Generated by Django 2.2.4 on 2020-07-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0033_auto_20200721_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='next_saison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prochaine_saison', to='ranking.Saison'),
        ),
        migrations.AlterField(
            model_name='saison',
            name='previous_saison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precedante_saison', to='ranking.Saison'),
        ),
    ]
