# Generated by Django 2.2.4 on 2020-07-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0035_auto_20200721_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='split_number',
            field=models.IntegerField(null=True),
        ),
    ]
