# Generated by Django 2.2.4 on 2020-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0036_saison_split_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Cacher la saison'),
        ),
    ]
