# Generated by Django 2.2.4 on 2020-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0038_messageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='elo_initial',
            field=models.IntegerField(default=1400),
        ),
        migrations.AlterField(
            model_name='messageinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archive', 'Archiver')], max_length=255),
        ),
    ]
